version: "3.8"
services:
  api:
    build: .
    image: perylemke/mastodon-api
    container_name: mastodon-api
    depends_on:
      - db
    environment:
      - DB_URI=mongodb
    ports:
      - "8080:8080"

  db:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
