version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  tests:
    docker:
      - image: cimg/python:3.8
    working_directory: ~/mastodon-api
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest -v --maxfail=1

workflows:
  sample:
    jobs:
      - tests
