version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest -v --maxfail=1

workflows:
  sample:
    jobs:
      - build-and-test
