version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  tests:
    docker:
      - image: cimg/python:3.8
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - setup_remote_docker
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: MongoDB Install
          command: |
            sudo apt-get install -y mongodb
      # - run:
      #     name: Run tests
      #     command: pytest -v --maxfail=1

workflows:
  sample:
    jobs:
      - tests
